### ISSUE TITLE
12B模型适配vllm

### ISSUE THREAD

**Issue by wkkkkkkkm** [Tele-AI/TeleChat-52B#3]
52B模型的vllm适配出了，能不能写个12B和7B的vllm适配

**Comment by shunxing12345** [comment]
您好，我们正在适配12b模型的vllm

**Comment by wkkkkkkkm** [comment]
@shunxing12345 好的，我现在是在52b的vllm文件上修改，出了很多问题。
类似：
IndexError: start out of range (expected to be in range of [-12288, 12288], but got 15360)
RuntimeError: start (10240) + length (10240) exceeds dimension size (12288)
用不同数量的显卡部署也会出现不同的错误。。。

**Comment by shunxing12345** [comment]
> @shunxing12345 好的，我现在是在52b的vllm文件上修改，出了很多问题。 类似： IndexError: start out of range (expected to be in range of [-12288, 12288], but got 15360) RuntimeError: start (10240) + length (10240) exceeds dimension size (12288) 用不同数量的显卡部署也会出现不同的错误。。。

您好 这个可以把错误截图发一下吗 另外方便提供您的运行环境的配置吗

**Comment by wkkkkkkkm** [comment]
发现出了12B的vllm了，感谢
